<script setup lang="ts">
const experiences = [{ role: 'Full Stack Engineer', company: 'PWR Pixel', date: 'June 2021 - Now', country: 'São José dos Campos, SP', description: '• Atuei como líder de equipe de desenvolvimento global e remoto, fornecendo treinamento e documentação didática (em inglês e português) para os novos desenvolvedores. \n • Forneci serviço de consultoria especializada em front-end para empresas de grande porte como 3 Corações, assim como para startups, entre elas a GlobalPro Fit, Codex e outras. \n • Atividades prestadas envolvem melhoria de uma aplicação em 50% de performance de carregamento. Redução de códigos em 45% com aplicação de clean code e boas práticas. Introdução de padrões de código tanto de commit quanto de desenvolvimento.\n • Participação ativa em code review e contratação de novos desenvolvedores.' }, { role: 'Full Stack Engineer', company: 'Ânima Educação', date: 'Outubro 2020 - Abril 2021', country: ' São Paulo, SP', description: '• Desenvolvimento de APIs em .NET para milhares de alunos da instituição Ânima, e criação de Gitflow e Artigos para uso interno. \n • Aplicação de padrões de design como DDD e princípios de software implementados no projeto como SOLID e Clean Code. \n • Realizei a implementação de tecnologias modernas como git commitizen e melhores práticas com XUnity (.NET Core).' }, { role: 'Lead Front End Developer', company: 'Pixfy', date: 'Junho 2020 - Maio 2021', country: 'Jacareí, SP', description: '• Liderei o time de front-end da Pixfy, entregando e conduzindo 3 projetos para startups, ONG`S e outras. \n • Desenvolvi e arquitetei projetos em VueJs, Sass, e outras tecnologias. \n • Responsável por todo o fluxo de criação dos projetos, passando desde o wireframe até a entrega final do website.' }, { role: 'Full Stack Developer', company: 'Agrotools', date: 'Julho 2020 - Outubro 2020', country: 'São José dos Campos, SP', description: '• Realizei o desenvolvimento de aplicativos mobile no setor de mapas e seguros agrícolas utilizando React-Native e C#. \n • Desenvolvi e implementei documentação sobre a configuração do ambiente, bem como mudanças rápidas e úteis para facilitar o trabalho dos funcionários' }, { role: 'Estagiário Full stack', company: 'Agrotools', date: 'Outubro 2018 - Julho 2020', country: 'São José dos Campos, SP', description: '• Realizei o desenvolvimento de aplicações utilizando Javascript, Jquery e também frameworks modernos incluindo Vue.js e React. \n • Implementação de recurso de tradução (i18n) no serviço de seguros e criação de rotas HTTP em APIs RESTFUL em C # .NET. \n • Realizei o desenvolvimento de ferramentas utilizando serviços de mapas (Open Layers). \n • Realizei o desenvolvimento de ferramentas que facilitavam a criação de consultas em banco em nível de usuário e desenvolvedor.' }]
</script>

<template lang="pug">
div(class="flex flex-col justify-center pt-2 pb-3 divide-y divide-gray-500")
  h1(class="text-xl font-bold text-start") Experiência
  ul
    li(class="pt-1" v-for="experience in experiences")
      h2(class="text-sm font-bold text-start") {{ experience.role}} | {{experience.company}} | {{experience.date}} | {{experience.country }}
      p(class="text-3.2 text-start pt-1 whitespace-pre-line") {{ experience.description }}
</template>

<style lang="scss" scoped>
</style>
