// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    StatsAndButtons: typeof import('./components/StatsAndButtons.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
  }
}

export { }
