// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Awards: typeof import('./components/Awards.vue')['default']
    Cv: typeof import('./components/Cv.vue')['default']
    CvHeader: typeof import('./components/CvHeader.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    Skills: typeof import('./components/Skills.vue')['default']
    StatsAndButtons: typeof import('./components/StatsAndButtons.vue')['default']
    Summary: typeof import('./components/Summary.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
  }
}

export { }
